### PR TITLE
Updated Sine and Cosine beam patterns

### LINKED ISSUE #128: Implement sine and cosine beams IAW sonobuoy production spec
Currently these beam patterns do not appear to include a frequency dependence.  If we can assume that these patterns are supposed to model the response of a dipole array.  Then the response should be

Cosine: B(a) = cos[ 2*pi*f / c * cos(a) ]
Sine: B(a) = cos[ 2*pi*f / c * sin(a) ]

a = conic angle from forward endfire
f = frequency
c = speed of sound

Reference: http://www.personal.psu.edu/faculty/m/x/mxm14/sonar/beamforming.pdf

### PR DESCRIPTION
**Pull request by Tibonium**
Resolves #128 
Added the ability to customize the cosine/sine pattern's null value and gain factor.

### CODE REVIEW

**Comment by campreilly** [comment]
Additional work is required.

**Comment by campreilly** [comment]
I'm looking for tests that demonstrate the acceptance criteria that I called out in the document C:\Development\Projects\usml_private\software_process\designs\Sine-Cosine Beam Directions.docx, and posted in issue #128.  Those criteria were:

* Demonstrate that for the special case of L = -10 dB, b(θ,ϕ,f,L,ϕ_r )=1/2 when ϕ-ϕ_r=63.6 degrees.
* Demonstrate that the beam pattern dips down in the northeast quadrant when a tilt of 20 degrees is applied in the 45 degree direction.
* Demonstrate that in the special case where L = -300 dB, the beam_pattern_model produces a directivity index such that DI(f,L)=10 log10(3).

Given all of the back and froth we've had on this one, and my earlier lack of clarity in defining this task, I just want to be sure that we have finally put this to bed.

**Comment by campreilly** [comment]
I'm looking at the Matlab routines in this test, trying to validate that the sine and cosine beams tilt in the right direction.  The routine that seems like it should do this is beam_pattern_cosine_sine.m, but without any comments in the code, I'm having trouble following what it is trying to show me.  

Here is what I get for the sine beam.
sine_beam
The sine_pattern_test code says that this is the beam pattern for pitch = 62, heading = 31, roll = 57.  How can I tell from this that the pattern "tilts" in the right direction?

Here is what I get for the cosine beam.
cosine_beam
Any idea why the lobe in the North-West corner looks smaller than the one in the South-East?  I thought that it might be a trick of perspective.  But it still seems mismatched when you rotate it.
cosine_beam

**Comment by Tibonium** [comment]
The answer to your question with regards to the sine pattern:
The regressions tests for the MRA, ie a response of 1.0, the two positions of the MRA are different from what are expected the test fails. This is noted in the comments. As for the matlab implementation, you should compare the results produced by the c++ implementation to the accepted matlab code. This is a visual check only.

With regards to the cosine pattern:
That is what the equation yields. Both in matlab and c++ implementation. So there are only two possibilities:
1. I have coded it wrong, ie the equation that is supposed to be peer reviewed is incorrect
2. the equation is missing something or our understanding is faulty

Dave

**Comment by campreilly** [comment]
Before I can accept this pull request, I’ll need you to resolve these two issues.

* In addition to whatever other tests we perform, I want to be sure that the sine and cosine beam tilt in an appropriate fashion when we use the tilt angle and tilt direction variants of array orientation.  So, as I state in part #2, “demonstrate that the beam pattern dips down in the northeast quadrant when a tilt of 20 degrees is applied in the 45 degree direction.”
* I don’t understand how equation (1) can support an asymmetry in the phi direction.  Especially give the evidence that it does not seem to be happening in the sine beam.  Please investigate why this is happening in the cosine beam.

**Comment by Tibonium** [comment]
Asymmetry: Consider when cosine is negative and how the equation does not account for this.
Orientation: Calling update_orientation with the two parameters requested, if I understand you correctly, will produce the results you are looking for. Doing this call prior to the double loop and before the calculation of _t and _p will also update the boost check regression.

**Comment by campreilly** [comment]
Dave says, "Asymmetry: Consider when cosine is negative and how the equation does not account for this."

Sean says, "Do you mean equation (1) in issue #128?"

**Comment by Tibonium** [comment]
Yep, that's the one. The second term can be negative.

**Pull request merged**
