### PR TITLE
Wavefront generator

### PR DESCRIPTION
**Pull request by islanderjtn**
Ongoing updates for wavefront_generator.

### CODE REVIEW

**Comment by campreilly** [comment]
I believe that I have successfully address all of the shared_ptr and mutwx issues in the usml::sensors package.  It is back up to the point where Ted had it working with one small exception: Have not yet attempted to execute logic in sensor_pair_manager_test,  But, I think this is good enough to share with other developers.

**Comment by islanderjtn** [comment]
This Pull Request resolves issues #132, #133, #134.

**Comment by Tibonium** [comment]
Pedantic appears to produce errors in both Windows and Linux. Without pedantic everything compiles.

**Comment by Tibonium** [comment]
Adding <code>#include &lt;set&gt;</code> to the sensor_model.h resolved these warnings.

**Pull request merged**
