### PR TITLE
Generate RPM installation package during builds

### PR DESCRIPTION
**Pull request by campreilly**
Added CPack commands to the CMakeLists file to support the generation of RPMs during make process.  We still want them to do their own compiles, so that things like compiler versions and shared libraries match the rest of their system. This capability allows them to use RPMs to support their own deliveries.  

The CPack process takes all of the data defined to support "make install" and converts it into an RPM file.  It automatically defines dependencies on Boost and NetCDF, using the version number discovered during the CMake build process.  To work correctly, you'll need to install both Boost and NetCDF from RPM so that it can use them both at compile time, and during installation.

Required a minor change to support Boost 1.41.  This version of boost did not support the ability to directly construct a vector<double> from the unbounded_array passed back from seq_vector.data().  This was a recent change (commit 62f6b9c4c0e277d9031043b6a9b15c49e68ecc01) that does not seem to be backward compatible.  It just required use to use std::copy to copy data from the unbounded_array into the vector<double>.  Super easy,

### CODE REVIEW

**Comment by campreilly** [comment]
To test:
* Reverted by computer to boost-devel-1.41 and netcdf-4.1.2, which I installed using the CentOS YUM server.
* Ran "make package" to generate the RPM.
* Ran "sudo rpm -ivh usml-2.0.0-dev.1.x86_64.rpm" to install the RPM.

```
[sreilly@sreilly usml]$ rpm -qa | grep boost
boost-devel-1.41.0-25.el6.centos.x86_64
boost-signals-1.41.0-25.el6.centos.x86_64
boost-python-1.41.0-25.el6.centos.x86_64
boost-graph-1.41.0-25.el6.centos.x86_64
boost-thread-1.41.0-25.el6.centos.x86_64
boost-serialization-1.41.0-25.el6.centos.x86_64
boost-system-1.41.0-25.el6.centos.x86_64
boost-test-1.41.0-25.el6.centos.x86_64
boost-wave-1.41.0-25.el6.centos.x86_64
boost-1.41.0-25.el6.centos.x86_64
boost-regex-1.41.0-25.el6.centos.x86_64
boost-program-options-1.41.0-25.el6.centos.x86_64
boost-iostreams-1.41.0-25.el6.centos.x86_64
boost-date-time-1.41.0-25.el6.centos.x86_64
boost-filesystem-1.41.0-25.el6.centos.x86_64
boost-math-1.41.0-25.el6.centos.x86_64
[sreilly@sreilly usml]$ rpm -qa | grep netcdf
netcdf-4.1.2-1.el6.rf.x86_64
netcdf-devel-4.1.2-1.el6.rf.x86_64
[sreilly@sreilly usml]$ make clean all package
[  1%] Generating /home/sreilly/Projects/usml/netcdf/test/etopo_cmp.nc, /home/sreilly/Projects/usml/netcdf/test/etopo_cmp.log
[  2%] Generating /home/sreilly/Projects/usml/netcdf/test/etopo_cmp2w.nc, /home/sreilly/Projects/usml/netcdf/test/etopo_cmp2w.log
[  3%] Generating /home/sreilly/Projects/usml/netcdf/test/etopo_cmp2e.nc, /home/sreilly/Projects/usml/netcdf/test/etopo_cmp2e.log
[  3%] Built target ETOPO_TEST_DATA
[  4%] Generating /home/sreilly/Projects/usml/netcdf/test/woa_cmp.nc, /home/sreilly/Projects/usml/netcdf/test/woa_cmp.log
[  5%] Generating /home/sreilly/Projects/usml/netcdf/test/woa_cmp2.nc, /home/sreilly/Projects/usml/netcdf/test/woa_cmp2.log
[  5%] Built target WOA_TEST_DATA
[  6%] Building CXX object CMakeFiles/usml.dir/ublas/randgen.cc.o
[  7%] Building CXX object CMakeFiles/usml.dir/ublas/trapfpe.cc.o
[  8%] Building CXX object CMakeFiles/usml.dir/types/wposition1.cc.o
[  9%] Building CXX object CMakeFiles/usml.dir/types/seq_vector.cc.o
[ 10%] Building CXX object CMakeFiles/usml.dir/types/wvector1.cc.o
[ 11%] Building CXX object CMakeFiles/usml.dir/types/wposition.cc.o
[ 12%] Building CXX object CMakeFiles/usml.dir/types/wvector.cc.o
[ 13%] Building CXX object CMakeFiles/usml.dir/netcdf/netcdf_bathy.cc.o
[ 14%] Building CXX object CMakeFiles/usml.dir/netcdf/netcdf_profile.cc.o
[ 15%] Building CXX object CMakeFiles/usml.dir/netcdf/netcdf_woa.cc.o
[ 16%] Building CXX object CMakeFiles/usml.dir/ocean/reflect_loss_netcdf.cc.o
[ 17%] Building CXX object CMakeFiles/usml.dir/ocean/attenuation_thorp.cc.o
[ 18%] Building CXX object CMakeFiles/usml.dir/ocean/profile_n2.cc.o
[ 19%] Building CXX object CMakeFiles/usml.dir/ocean/reflect_loss_beckmann.cc.o
[ 20%] Building CXX object CMakeFiles/usml.dir/ocean/profile_munk.cc.o
[ 21%] Building CXX object CMakeFiles/usml.dir/ocean/profile_model.cc.o
[ 22%] Building CXX object CMakeFiles/usml.dir/ocean/boundary_slope.cc.o
[ 23%] Building CXX object CMakeFiles/usml.dir/ocean/reflect_loss_rayleigh_grid.cc.o
[ 24%] Building CXX object CMakeFiles/usml.dir/ocean/ocean_shared.cc.o
[ 25%] Building CXX object CMakeFiles/usml.dir/ocean/profile_linear.cc.o
[ 26%] Building CXX object CMakeFiles/usml.dir/ocean/boundary_flat.cc.o
[ 27%] Building CXX object CMakeFiles/usml.dir/ocean/profile_catenary.cc.o
[ 28%] Building CXX object CMakeFiles/usml.dir/ocean/attenuation_constant.cc.o
[ 29%] Building CXX object CMakeFiles/usml.dir/ocean/reflect_loss_rayleigh.cc.o
[ 30%] Building CXX object CMakeFiles/usml.dir/ocean/ascii_profile.cc.o
[ 31%] Building CXX object CMakeFiles/usml.dir/ocean/ascii_arc_bathy.cc.o
[ 32%] Building CXX object CMakeFiles/usml.dir/sensors/orientation.cc.o
[ 33%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_solid.cc.o
[ 34%] Building CXX object CMakeFiles/usml.dir/sensors/sensor_manager.cc.o
[ 35%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_VLA.cc.o
[ 36%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_multi.cc.o
[ 37%] Building CXX object CMakeFiles/usml.dir/sensors/sensor_pair_manager.cc.o
[ 38%] Building CXX object CMakeFiles/usml.dir/sensors/receiver_params.cc.o
[ 39%] Building CXX object CMakeFiles/usml.dir/sensors/sensor_pair.cc.o
[ 40%] Building CXX object CMakeFiles/usml.dir/sensors/orientation_HLA.cc.o
[ 41%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_cosine.cc.o
[ 42%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_sine.cc.o
[ 43%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_omni.cc.o
[ 44%] Building CXX object CMakeFiles/usml.dir/sensors/sonobuoy.cc.o
[ 45%] Building CXX object CMakeFiles/usml.dir/sensors/source_params_map.cc.o
[ 46%] Building CXX object CMakeFiles/usml.dir/sensors/fathometer_model.cc.o
[ 47%] Building CXX object CMakeFiles/usml.dir/sensors/receiver_params_map.cc.o
[ 48%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_map.cc.o
[ 49%] Building CXX object CMakeFiles/usml.dir/sensors/source_params.cc.o
[ 50%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_HLA.cc.o
[ 51%] Building CXX object CMakeFiles/usml.dir/sensors/orientation_VLA.cc.o
[ 52%] Building CXX object CMakeFiles/usml.dir/sensors/beam_pattern_line.cc.o
[ 53%] Building CXX object CMakeFiles/usml.dir/sensors/sensor_model.cc.o
[ 54%] Building CXX object CMakeFiles/usml.dir/eigenverb/envelope_collection.cc.o
[ 55%] Building CXX object CMakeFiles/usml.dir/eigenverb/eigenverb_collection.cc.o
[ 56%] Building CXX object CMakeFiles/usml.dir/eigenverb/envelope_generator.cc.o
[ 57%] Building CXX object CMakeFiles/usml.dir/eigenverb/eigenverb_interpolator.cc.o
[ 58%] Building CXX object CMakeFiles/usml.dir/eigenverb/eigenverb_notifier.cc.o
[ 59%] Building CXX object CMakeFiles/usml.dir/eigenverb/envelope_notifier.cc.o
[ 60%] Building CXX object CMakeFiles/usml.dir/eigenverb/wavefront_generator.cc.o
[ 61%] Building CXX object CMakeFiles/usml.dir/eigenverb/envelope_model.cc.o
[ 62%] Building CXX object CMakeFiles/usml.dir/threads/thread_controller.cc.o
[ 63%] Building CXX object CMakeFiles/usml.dir/threads/thread_task.cc.o
[ 64%] Building CXX object CMakeFiles/usml.dir/threads/thread_pool.cc.o
[ 65%] Building CXX object CMakeFiles/usml.dir/waveq3d/wave_queue_netcdf.cc.o
[ 66%] Building CXX object CMakeFiles/usml.dir/waveq3d/ode_integ.cc.o
[ 67%] Building CXX object CMakeFiles/usml.dir/waveq3d/eigenray_notifier.cc.o
[ 68%] Building CXX object CMakeFiles/usml.dir/waveq3d/spreading_ray.cc.o
[ 69%] Building CXX object CMakeFiles/usml.dir/waveq3d/wave_queue.cc.o
[ 70%] Building CXX object CMakeFiles/usml.dir/waveq3d/spreading_hybrid_gaussian.cc.o
[ 71%] Building CXX object CMakeFiles/usml.dir/waveq3d/eigenray_collection.cc.o
[ 72%] Building CXX object CMakeFiles/usml.dir/waveq3d/wave_front.cc.o
[ 73%] Building CXX object CMakeFiles/usml.dir/waveq3d/reflection_model.cc.o
Linking CXX shared library libusml.so
[ 73%] Built target usml
[ 74%] Building CXX object CMakeFiles/usml_test.dir/usml_test.cc.o
[ 75%] Building CXX object CMakeFiles/usml_test.dir/ublas/test/matrix_test.cc.o
[ 76%] Building CXX object CMakeFiles/usml_test.dir/ublas/test/randgen_test.cc.o
[ 77%] Building CXX object CMakeFiles/usml_test.dir/ublas/test/vector_test.cc.o
[ 78%] Building CXX object CMakeFiles/usml_test.dir/types/test/sequence_test.cc.o
[ 79%] Building CXX object CMakeFiles/usml_test.dir/types/test/quadtree_test.cc.o
[ 80%] Building CXX object CMakeFiles/usml_test.dir/types/test/datagrid_test.cc.o
[ 81%] Building CXX object CMakeFiles/usml_test.dir/types/test/position_test.cc.o
[ 82%] Building CXX object CMakeFiles/usml_test.dir/netcdf/test/read_bathy_test.cc.o
[ 83%] Building CXX object CMakeFiles/usml_test.dir/netcdf/test/read_profile_test.cc.o
[ 84%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/boundary_test.cc.o
[ 85%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/attenuation_test.cc.o
[ 86%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/reflect_loss_test.cc.o
[ 87%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/profile_test.cc.o
[ 88%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/boundary_lock_test.cc.o
[ 89%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/profile_lock_test.cc.o
[ 90%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/ocean_shared_test.cc.o
[ 91%] Building CXX object CMakeFiles/usml_test.dir/ocean/test/volume_lock_test.cc.o
[ 92%] Building CXX object CMakeFiles/usml_test.dir/sensors/test/maps_test.cc.o
[ 93%] Building CXX object CMakeFiles/usml_test.dir/sensors/test/sensor_manager_test.cc.o
[ 94%] Building CXX object CMakeFiles/usml_test.dir/sensors/test/beam_pattern_test.cc.o
[ 95%] Building CXX object CMakeFiles/usml_test.dir/eigenverb/test/eigenverb_test.cc.o
[ 96%] Building CXX object CMakeFiles/usml_test.dir/threads/test/threads_test.cc.o
[ 97%] Building CXX object CMakeFiles/usml_test.dir/waveq3d/test/refraction_test.cc.o
[ 98%] Building CXX object CMakeFiles/usml_test.dir/waveq3d/test/proploss_test.cc.o
[ 99%] Building CXX object CMakeFiles/usml_test.dir/waveq3d/test/reflection_test.cc.o
[100%] Building CXX object CMakeFiles/usml_test.dir/waveq3d/test/eigenray_test.cc.o
Linking CXX executable usml_test
[100%] Built target usml_test
Run CPack packaging tool...
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: usml
CPack: - Install project: usml
CPack: Create package
CPackRPM: Will use GENERATED spec file: /home/sreilly/workspace/usml/_CPack_Packages/Linux/RPM/SPECS/usml.spec
CPack: - package: /home/sreilly/workspace/usml/usml-2.0.0-dev.1.x86_64.rpm generated.
[sreilly@sreilly usml]$ sudo rpm -ivh usml-2.0.0-dev.1.x86_64.rpm
[sudo] password for sreilly: 
Preparing...                ########################################### [100%]
   1:usml                   ########################################### [100%]

```

**Comment by campreilly** [comment]
CMake seems to be doing a pretty good job of limiting RPM dependencies to just the minimum.
```
[sreilly@sreilly usml]$ rpm -qpR usml-2.0.0-dev.1.x86_64.rpm
/bin/sh  
/bin/sh  
/bin/sh  
/bin/sh  
config(usml) = 2.0.0_dev.1-1
libboost_system-mt.so.5()(64bit)  
libboost_thread-mt.so.5()(64bit)  
libboost_unit_test_framework-mt.so.5()(64bit)  
libc.so.6()(64bit)  
libc.so.6(GLIBC_2.2.5)(64bit)  
libc.so.6(GLIBC_2.3.2)(64bit)  
libgcc_s.so.1()(64bit)  
libgcc_s.so.1(GCC_3.0)(64bit)  
libm.so.6()(64bit)  
libm.so.6(GLIBC_2.2.5)(64bit)  
libnetcdf.so.7()(64bit)  
libnetcdf_c++.so.4()(64bit)  
libstdc++.so.6()(64bit)  
libstdc++.so.6(CXXABI_1.3)(64bit)  
libstdc++.so.6(GLIBCXX_3.4)(64bit)  
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)  
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)  
libusml.so.2.0.0-dev.1()(64bit)  
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)  
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by campreilly** [comment]
Ready for peer review.

**Comment by islanderjtn** [comment]
Works great!

**Pull request merged**
