### PR TITLE
Beam pattern orientation

### PR DESCRIPTION
**Pull request by Tibonium**
Added tri-axis rotational capability to beam patterns. Created a new class orientation, that takes a pitch, heading, and roll, stores them locally and then allows the user to request/update them as needed. The user then requests a rotation about a reference axis by calling apply_rotation. The reference axis is rotated in a cartesian system by the pitch/heading/roll and then converted to a spherical vector. The theta and phi values of this vector are then returned to the user.

Beam pattern classes have been updated to now use this new orientation class and tests have been updated. Vertical/Horizontal array test checks now only that the directivity index is unchanged and the pitch/heading/roll are set to zero for a beam pattern of solid angle. This is done as the directivity index changes with the rotations, as it should, but a method for updating the directivity index has yet to be added.

This addresses #135

### CODE REVIEW

**Comment by campreilly** [comment]
You say, "the directivity index changes with the rotations, as it should".

But, the directivity index should not change with rotations.  Just with changes in steering direction.

**Comment by Tibonium** [comment]
Consider what it means to have a rotation on a solid angle on a sphere.

On Apr 2, 2015 6:56 PM, Sean Reilly <notifications@github.com> wrote:

You say, "the directivity index changes with the rotations, as it should".

But, the directivity index should not change with rotations. Just with changes in steering direction.

—
Reply to this email directly or view it on GitHub<https://github.com/campreilly/UnderSeaModelingLibrary/pull/137#issuecomment-89068904>.

The information contained in this message, and any attachments, may contain privileged and/or proprietary information that is intended solely for the person or entity to which it is addressed. Moreover, it may contain export restricted technical data controlled by Export Administration Regulations (EAR) or the International Traffic in Arms Regulations (ITAR). Any review, retransmission, dissemination, or re-export to foreign or domestic entities by anyone other than the intended recipient in accordance with EAR and/or ITAR regulations is prohibited.

**Comment by Tibonium** [comment]
<a href="http://en.wikipedia.org/wiki/Active_and_passive_transformation">Active (alias) and Passive (alibi) rotations</a>.

**Comment by campreilly** [comment]
I'm having a problem getting this branch to compile.

```
In file included from /home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:6:
/home/sreilly/Projects/usml/../usml/sensors/sensors.h:36:49: error: usml/sensors/sensor_params::id_type.h: No such file or directory
/home/sreilly/Projects/usml/../usml/sensors/sensors.h:43:39: error: usml/sensors/sensorIDType.h: No such file or directory
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc: In member function ‘void reverb_analytic_test::define_sensor_characteristics()’:
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:95: error: no matching function for call to ‘usml::sensors::beam_pattern_map::insert(int, usml::sensors::beam_pattern_omni*)’
/home/sreilly/Projects/usml/../usml/sensors/sensor_map_template.h:65: note: candidates are: bool usml::sensors::sensor_map_template<key_type, mapped_type>::insert(key_type, mapped_type) [with key_type = int, mapped_type = boost::shared_ptr<usml::sensors::beam_pattern_model>]
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:99: error: ‘beamIDType’ was not declared in this scope
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:99: error: template argument 1 is invalid
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:99: error: template argument 2 is invalid
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:99: error: invalid type in declaration before ‘;’ token
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:100: error: request for member ‘push_back’ in ‘source_beams’, which is of non-class type ‘int’
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:108: error: no matching function for call to ‘usml::sensors::source_params::source_params(int, double, double, double, double, int&)’
/home/sreilly/Projects/usml/../usml/sensors/source_params.h:63: note: candidates are: usml::sensors::source_params::source_params(const usml::sensors::source_params&)
/home/sreilly/Projects/usml/../usml/sensors/source_params.h:56: note:                 usml::sensors::source_params::source_params(usml::sensors::sensor_params::id_type, bool, double, const usml::types::seq_vector&, usml::sensors::beam_pattern_model::id_type)
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:109: error: no matching function for call to ‘usml::sensors::source_params_map::insert(int, usml::sensors::source_params*&)’
/home/sreilly/Projects/usml/../usml/sensors/sensor_map_template.h:65: note: candidates are: bool usml::sensors::sensor_map_template<key_type, mapped_type>::insert(key_type, mapped_type) [with key_type = int, mapped_type = boost::shared_ptr<usml::sensors::source_params>]
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:113: error: ‘beamIDType’ cannot appear in a constant-expression
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:113: error: template argument 1 is invalid
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:113: error: template argument 2 is invalid
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:113: error: invalid type in declaration before ‘;’ token
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:114: error: request for member ‘push_back’ in ‘receiver_beams’, which is of non-class type ‘int’
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:116: error: no matching function for call to ‘usml::sensors::receiver_params::receiver_params(int&)’
/home/sreilly/Projects/usml/../usml/sensors/receiver_params.h:59: note: candidates are: usml::sensors::receiver_params::receiver_params(const usml::sensors::receiver_params&)
/home/sreilly/Projects/usml/../usml/sensors/receiver_params.h:53: note:                 usml::sensors::receiver_params::receiver_params(usml::sensors::sensor_params::id_type, bool, const std::list<int, std::allocator<int> >&)
/home/sreilly/Projects/usml/studies/reverberation/reverb_analytic_test.cc:117: error: no matching function for call to ‘usml::sensors::receiver_params_map::insert(int, usml::sensors::receiver_params*&)’
/home/sreilly/Projects/usml/../usml/sensors/sensor_map_template.h:65: note: candidates are: bool usml::sensors::sensor_map_template<key_type, mapped_type>::insert(key_type, mapped_type) [with key_type = int, mapped_type = boost::shared_ptr<usml::sensors::receiver_params>]
make[2]: *** [CMakeFiles/reverb_analytic_test.dir/studies/reverberation/reverb_analytic_test.cc.o] Error 1
make[1]: *** [CMakeFiles/reverb_analytic_test.dir/all] Error 2
make: *** [all] Error 2
````

**Comment by campreilly** [comment]
Studies was the problem.

**Pull request merged**
