### PR TITLE
Add EnvelopeGeneration

### LINKED ISSUE #180: Compute beam pattern gains in envelope_generator
Replace the scalar_matrix versions of src_beam and rcv_beam with real beam pattern results in envelope_generator::run().

### PR DESCRIPTION
**Pull request by islanderjtn**
Resolves #180 and #210.
Added envelope_listener and implemented in sensor_pair.
Note: This is not fully implemented.  Issue remains with envelope calculations. reverb_analytic_test will produce envelope nc file however many locations where required to be hard-code to debug.  All TODO  need to be addressed when envelope calcutations are resolved.

### CODE REVIEW

**Comment by campreilly** [comment]
Functionality changes:
* Create sensor_pair::run_envelope_generator() and have it actually run the envelope_generator.  These two were not integrated before,
* Added source_id and receiver_id to envelope_collection constructor.
* Replace many of the arguments in the envelope_generator constructor with a reference to the sensor_pair that is launching the thread task.
* Make sensor_pair an envelope_listener in the constructor of envelope_generator.
* Create two versions of the envelope_generator with different lists of parameters.
* Temporarily limit envelope_generator::run() calculation to bottom interface and az_index=0.  Just for help in debugging.
* Allow envelope_generator::scattering() to return false if scattering strength is not valid.  Modified envelope_generator::run() to respect this value, but did not implement the actual validity check yet.
* Compute source and receiver beam levels for eigenverbs instead of using dummy values in envelope_generator::run().
* Temporarily add a large number of debugging print statements to envelope_model::compute_overlap() function.  
* Temporarility modify wavefront_generator to create the same ray fans as eigenverb_demo.m test.
* Add scattering() method to boundary_lock class.  Without this, the reverb_analytic_test always uses the default scattering model instead of scattering_lambert.
* Remove the "_" prefix from the names of the depth_guard and scattering_guard variables in ~volume_lock() to reflect the fact that these are local variables.
* Remove eigenverb_collection* _collection variable from wave_queue.  This functionality has been moved to eigenray_notifier class.
* Fix spacing in comments to reflect the fact that we should all be inserting spaces instead of tabs now.

**Comment by campreilly** [comment]
A quick note from the Office of Continuous Process Improvement...

When we create a pull request, I'd like to see a more detailed description of the developers intent for these changes.  I was able to glean the changes in the previous comment during my peer review of the code.  But having these written out may be important for those who are just browsing the commit e-mails.  And, it may make outr jobs much easier when the time comes to produce release notes.

**Comment by campreilly** [comment]
Two technical questions about these changes:
* Why do we need two versions of the envelope_generator with different lists of parameters?
* Now that we are passing a reference to the sensor_pair into the envelope_generator constructor, why do we need any of the other arguments.  Don't those all come from the sensor_pair object?

**Comment by islanderjtn** [comment]
Second envelope_generator constructor is just their to be used in eigebverb_test/envelope basic. 
The first envelope_generator constructor should be modified to just pass the sensor_pair. All needed parameters come from the sensor_pair

**Comment by campreilly** [comment]
Modified envelope_generator constructor to eliminate arguments that can be deduced from public accessors in the sensor_pair* that is already has.

Change the name of the sensor_pair utility that builds the intersecting frequencies from frequencies() to compute_frequencies. This keeps it from colliding with the public acessor for the _frequencies property, which was also called frequencies().

**Comment by campreilly** [comment]
Peer review complete.
* Reviewed the source code, and agree with design choices
* Both usml_test and reverb_analytic test run without errors.
* But envelope_generator does not accurately reproduce the results of the eigenverb_demo.m test. Created issue #215 to track that problem.

**Pull request merged**
