### PR TITLE
Use RTrees to Cull source eigenverbs down to a reasonable amount

### PR DESCRIPTION
**Pull request by islanderjtn**
Implemented boost rtrees in eigenverb_collection. 
One rtree for each volume interface.

Just before sensor_model passes the src_eigenverbs to the sensor_pair the generate_rtrees is called on the eigenverb_collection.  

generate_rtrees uses the packing algorthym constructor of Boost rtree. This provides the fastest insertion times as well as the fastest query's.  A local std::list<std::pair<point, eigenverb_list::iterator>> is created and inserted in one call to the rtree constructor, as apposed to n insert() calls.
The point is just the center lat,lon of the each eigenverb and the eigenverb_list::iterator is the pointer to  the eigenverb data.

Envelope_generator.run was modified to use the rtree.query() call using a bounding box of the receiver eigenverb to select all the src point's within the box.  Initially approxiately 6700 src eigenverbs, and approx 6000 rcv eigenverbs took over 92 sec to process. Three other culling methods are used to reduce processing down to alitte over 28 sec. Using the rtrees reduced this processing to approx 4.0 sec +- 0.15 sec

### CODE REVIEW

**Comment by campreilly** [comment]
Can you explain why we changed the eigenverb_collection::add-eigenverb() method from
```
    void add_eigenverb(const eigenverb& verb, size_t interface) {
        _collection[interface].push_back(verb);
    }
```
to
```
    void add_eigenverb(const eigenverb& verb, size_t interface) {

        // Add to collection
        eigenverb_list::iterator iter;
        iter = _collection[interface].insert(_collection[interface].end(), verb);
    }
```

**Comment by islanderjtn** [comment]
Sean,
                I wanted to insert directly into rtree here, once for each eigenverb .  Needed the iterator value to perform the insert into rtree.
                We’ll not be inserting one at a time, so no we should revert to the push_back instead of the insert.
Ted

**Comment by campreilly** [comment]
This branch does not compile on my Linux machine.  There appears to be a bug in the boost::geometry package in 1.56 and 1.57.

https://svn.boost.org/trac/boost/ticket/10467

This problem did not appear in Boost 1.55 and was fixed in Boost 1.58

https://svn.boost.org/trac/boost/ticket/10467

I can see two ways to fix this.  Avoid versions 1.56 and 1.57, or patch them to use the fix delivered in 1.58.

**Comment by campreilly** [comment]
I have a few issues with rtree_test.cc
- No documentation provided for rtree_test/rtree_basic.  Please correct this.
- I see that you rely on the eigenverb files created by eigenverb_basic, and that prevents this test from being run in a stand-alone mode.  How should we be warning the users of this?
- Should rtree_test be its own suite, or should it be under eigenverb_test?

**Comment by campreilly** [comment]
Bug: I can run almost all of the tests ust fine in Linux, but I'm seeing the following error in reverb_analytic_test.

```
[sreilly@sreilly usml]$ reverb_analytic_test
== define ocean characteristics ==
== define sensor characteristics ==
== deploy sensor instance ==
******
sensor_manager: add sensor(1)
sensor_pair_manager: add sensor(1)
   add_monostatic_pair: sensor_pair(1,1)
sensor_pair_manager:  current pairs
     pair  src_rcv 1_1
******
sensor_manager: update sensor(1)
sensor_model: update_sensor(1)
sensor_model: run_wave_generator(1)
== wait for results ==
sensor_model: update_wavefront_data(1)
sensor_model: update_wavefront_data eigenray list size 16
sensor_pair: update_fathometer(1)
sensor_pair: update_eigenverbs(1)
sensor_pair: run_envelope_generator 
waited for 10 secs
== test complete ==
Uncaught exception in thread_task: boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```
Note that this is using the Boost 1.58 libraries.  I get the same result in either Release or Debug mode.  I have not yet had any luck getting the Eclipse debugger to trap this error.

**Comment by campreilly** [comment]
Apparently, reverb_analytic_test is failing to run (see mutex lock failed error above) because it is exiting before the threads have completed their work.  I'll enter this as a bug issue and not count it against this pull request.

**Comment by islanderjtn** [comment]
Removed rtree_test as a standalone test and placed in the eigenverb_test file as it requires files generated by the eigenverb_basic test. Updated rtree_basic test to more closely resemble the production code and provided comments on the test.

**Comment by campreilly** [comment]
Still working to get the Boost 1.58 library to compile and execute correctly in Visual Studio 12.0 on Windows.

**Comment by campreilly** [comment]
Note that when Visual Studio 12 is used in Debug mode, it exhibited errors corrected in the vs2010errors branch.  We assume that these errors will be corrected when these two efforts are merged.
```
=== sequence_test/seq_augment_test ===
origin: [5](6,6.7839278,7.6846584,8.7389332,10)
augment: [11](6,6.1959819,6.3919639,6.5879458,6.7839278,-1.456816e+144,-1.456816e+144,-1.456816e+144,-1.456816e+144,-1.456816e+144,10)
C:/Development/Projects/usml/types/test/sequence_test.cc(607): error in "seq_augment_test": difference{1.89575e+145%} between i{-1.4568159901474629e+144} and tmp[index++]{7.68466} exceeds 0.0001%
C:/Development/Projects/usml/types/test/sequence_test.cc(607): error in "seq_augment_test": difference{1.66704e+145%} between i{-1.4568159901474629e+144} and tmp[index++]{8.7389299999999999} exceeds 0.0001%
C:/Development/Projects/usml/types/test/sequence_test.cc(607): error in "seq_augment_test": difference{1.63047e+145%} between i{-1.4568159901474629e+144} and tmp[index++]{8.93492} exceeds 0.0001%
C:/Development/Projects/usml/types/test/sequence_test.cc(607): error in "seq_augment_test": difference{1.59548e+145%} between i{-1.4568159901474629e+144} and tmp[index++]{9.1309000000000005} exceeds 0.0001%
C:/Development/Projects/usml/types/test/sequence_test.cc(607): error in "seq_augment_test": difference{1.56195e+145%} between i{-1.4568159901474629e+144} and tmp[index++]{9.3268799999999992} exceeds 0.0001%
```

**Pull request merged**
