### PR TITLE
Improve envelope accuracy

### PR DESCRIPTION
**Pull request by campreilly**
Update calculation of eigenverb length, width, and area based on spacing halfway to next and previous rays
- Update wave_queue::build_eigenverb() to compute area, de_delta, az_delta
- Write a long description of this method as part of doxygen comments for wave_queue::build_eigenverb() method.  Include equations.
- Update eigenverb_test routines to compute values this way.
- Update eigenverb_test/eigenverb_analystic test to better match  eigenverb_demo.m scenario. Computes reverb using only a single AZ.
- Support both length/width and length/width squared in eigenverb.

Correct the definition of xs/ys in envelope_generator.cc
- ys is the downrange term with cos(bearing)
- xs is the cross-range term with sin(bearing)
- they had been reversed.

Remove frequency dependence from eigenverb length and width.
- Change the data type of eigenverb.length2 and eigenverb.width2 from vector<double> to double.
- Change the name of eigenverb.energy to power.
- Update eigenverb_collection::write_netcdf to reflect this changes.
- Convert length2 and width2 from vectors to scalars in eigenray_interpolator.
- Don't initialize vectors for length2 and width2 in envelope_generator.
- Have spatial thresholds in envelope_generator use scalar versions of length2 and width2 instead of first element of vector.
- Convert length2 and width2 from vectors to scalars in envelope_model::compute_overlap().
- Change _duration from a vector to a scalar in envelope_model.
- Convert length2 and width2 from vectors to scalars in wave_queue::build_eigenerb(),
- Convert length2 and width2 from vectors to scalars in eigenverb_test.
- Update Matlab load_eigenverbs.m to reflect new C++ code.

Move wave_queue thresholds to their own class.
- Add thresholds for caustics, upper, lower.
- Add routines to test thresholds.
- Modify wave_queue to use this version of thresholding routines.

Add bearing calculation to greatCircleDistance.m
- Build test routine that uses Aviation Formulary worked example from LAX to JFK airports.
- Avoid cases in which round off error cause acos() to return imaginary values.

Update eigenverb and envelop calculation to match eigenverb_demo.m
- Compute power as function of initial area and attenuation in wave_queue::build_eigenverb().
- Correct math error in calcuation of kappa in compute_overlap(). There was a "*" that should have been a "+". Put all factors for kappa calculation in the same equation.
- Correct the equation for normalizing angle in envelope_model::compute_intensity().
- Reorganize wave_queue::build_eigenverb() to start with power calc so that more operations are skipped if power below threshold.
- Calling _spreading_model->width_de() with a de index equal to _max_de was causing an index out of bounds error in uBLAS.
- Create a new test called eigenverb_test/eigenverb_analytic that is specifically designed to create eigenverb netCDF files for comparison to eigenverb_demo.m Matlb script.
- Create a new Matlab test called envelope_demo.m that computes envelopes from the data created by eigenverb_analytic.
- Add distance_threshold as a control parameter to envelope_generator.
- Remove unused constructor from envelope_generator.
- Don't threshold on scattering strength.
- Don't normalize eigenverb tilt or bearing between source and receiver eigenverb.
- Fixed error in envelope_model.  The src_prod variable was being
  reassigned during the calculation of kappa.  But the duration calc
  assumed it still had the old value. Mark many of the temporary variables
  in envelope_model::compute_overlap() as const to avoid this problem in the future.
- Fix error in envelope_basic theory test.  Factor of 2 should have been
  a factor of 4 in denominator.
- Change envelope_basic test condition from BOOST_CHECK_CLOSE
  with 0.01% error to BOOST_CHECK_SMALL with 0.0001 dB error.
- Write pulse_length, threshold, and initial_time to netCDF envelope files.
- Remove un-used "level" variable from envelope_model
- Rename "collections" to "envelopes" in eigenverb_test.cc
- Add const statements to envelope_collection.h

Create a new study called studies/reverberation/reverb_extra_test
- Artificially limit processing to downward D/E launch
  angles and receivers AZ launch angles to zero to match the conditions
  used in eigenverb_demo.m.
- Artificially limit the initial time (using the round trip time to
  bottom) to test the ability to limit the initial time. Such a limitation is
  not normally used for a monostatic sensor.
- Set threshold to 1e-17 and use 18 source AZ angles.

Merged with changes for add_rtree_query and vs2010errors.

Supports issue #215

### CODE REVIEW

**Comment by campreilly** [comment]
Not yet ready for peer review.

**Comment by campreilly** [comment]
Interesting - dead_reckon_test take 250 sec in Debug and 6 sec in Release.

**Comment by campreilly** [comment]
This pull request is ready for peer review.
- In Release mode under Linux, I've tested usml_test, cmp-speed, dead_reckon_test, eigenray_extra_test, pedersen_test, reverb_analytic_test, and reverb_extra-test.
- In Debug mode mode under Linux, I've tested usml_test.

**Comment by islanderjtn** [comment]
Found Valgrind errors in eigenverb_collection::read_netcdf call.
Effected eigenverb_test/rtree_basic test only.
Updated as required.
All other changes were reviewed.
Tested all regression test and modified studies for Debug and Release on MSVS12 64 bit and RHEL Gnu 64 bit.
All tests were successful.

**Pull request merged**
