### PR TITLE
New beam pattern model that allows for multiple patterns

### PR DESCRIPTION
**Pull request by Tibonium**
Resolves issue #156 
With the addition of this class, a beam pattern can now be constructed from a series of beam patterns. Each pattern is stored in a list within the new class and when beam level is called, the beam level from each pattern in the list is multiplied together and returned. The directivity index is computed in a similar fashion.

### CODE REVIEW

**Comment by campreilly** [comment]
Does this class allow the first beam pattern to specify its angles in D/E and the second to specify its angles in AZ?

**Comment by Tibonium** [comment]
Are you talking about a beam_pattern_solid? or are you referring to two beam_pattern_grid 1-D?

**Comment by campreilly** [comment]
Referring to a beam_pattern_model that combines different horizontal and vertical patterns. Issue #156.  Like beam_pattern_solid, but with an actual shape in the horizontal and vertical.  Or an actual beam pattern in vertical, and a "cookie cutter" pattern like beam_pattern_solid in the horizontal.

**Comment by Tibonium** [comment]
I can't think of any reason why you wouldn't make a beam_pattern_grid in this scenario. It sounds like you want to create two 1-D grids and preserve the rotation nature in each dimension independently of each other, which doesn't make sense with the requirement of strict dimension ordering in grids. how else would we know which dimension corresponds to which orientation?

**Comment by campreilly** [comment]
Imagine a case in which you were comparing results from another model, like CASS.  And in that model, they specified the verical beam pattern as a table, and the horizontal beam pattern as a constant between two angles.

It also turns out that for many arrays, the beam patterns in each direction are separable, For example: a cylindrical array can be modeled as the product of a line array for each vertical stave with the pattern for a circle of elements in the horizontal.

**Pull request merged**
