### PR TITLE
Relocate frequencies

### PR DESCRIPTION
**Pull request by islanderjtn**
Added seq_linear frequencies property to sensor_model manipulated by min/max active frequencies.
Added beam_list to source_params.
Changed sensor_pair to hold fathometer_model vs eigenrays.
Added  std::vector frequencies property to sensor_pair based on the intersection of receiver frequencies and source frequencies.
Added to sensor_manager_test to verify changes.

### CODE REVIEW

**Comment by islanderjtn** [comment]
Hold off until #176 is completed.

**Comment by islanderjtn** [comment]
Ready for Merge #176 is completed.
Added seq_vector_clip_test to sequence_test. 
To test merge run seq_vector_clip_test, sensor_manger_test, and read_bathy_test

**Comment by campreilly** [comment]
Most of this work was completed as part of the relocate_frequencies branch.  Parts that remain were split into their own issues.

**Comment by campreilly** [comment]
Error - I meant to close issue #174, not this pull request.

**Comment by campreilly** [comment]
Question about fathometer ownership.

The eigenray list for the fathometers are pulled from an eigenray_collection on line 132 of sensor_model.cc
```
        if (iter != _target_id_map.end()) {
            read_lock_guard guard(_eigenrays_mutex);
            int row = iter->second;
            // Get eigenray_list for listener, ie sensor_pair
            // Get complement's row's eigenray_list
            eigenray_list* list = _eigenray_collection->eigenrays(row, 0);
             // Send out eigenray_list to listener
            listener->update_fathometer(_sensorID, list);
	}
```
Then update_fathometer uses it to create a new shared_ptr<fathometer_model>.on line 49 of sensor_pair.cc.
```
    if ( list != NULL ) {
        if (sensorID == _receiver->sensorID()) {
            BOOST_FOREACH(eigenray ray, *list) {
                std::swap(ray.source_de, ray.target_de);
                std::swap(ray.source_az, ray.target_az);
            }
        }
        // Note new memory location for eigenrays is create here
        _fathometer = shared_ptr<fathometer_model>(new fathometer_model(_source->sensorID(), 
            _receiver->sensorID(), _source->position(), _receiver->position(), *list));
    }
```
Why doesn't the reference to this eigenray list get invalidated when the eigenray_collection in the sensor_model is replaced?

**Comment by campreilly** [comment]
Retract my last comment.  Because the eigenray_list is passed to the fathometer_model constructor by value, it is actually performing a clone operation.
```
 fathometer_model(sensor_model::id_type source_id, sensor_model::id_type receiver_id,
                     wposition1 src_pos, wposition1 rcv_pos, eigenray_list list )
        : _source_id(source_id), _receiver_id(receiver_id), _slant_range(0.0), 
        _distance_from_sensor(0.0), _depth_offset_from_sensor(0.0),
        _source_position(src_pos), _receiver_position(rcv_pos), _eigenrays(list)
     {}
```
The statement that says ```_eigenrays(list)``` actually makes a new ```std::list< eigenray >``` and then clones each structure in ```list``` and places the clone in ```_eigenrays```.

**Comment by islanderjtn** [comment]
Sean,
                I believe the call


new fathometer_model(_source->sensorID(),
            _receiver->sensorID(), _source->position(), _receiver->position(), *list)

Makes a copy of the *list in the constructor.
Ted

**Comment by campreilly** [comment]
It appears our emails passed each other in the night.  I came to the same conclusion.

**Comment by campreilly** [comment]
During this peer review I...
* Reviewed the code under "files changed", looking for flaws in the implementer's logic.
* Checked to see that new functionality was associated with unit test changes that exercised its likely failure modes.
* Compiled the tests and studies under Linux, in both Debug and Release mode, with --pedantic turned on.
* Executed usml_test under Linux, in both Debug and Release mode.  No errors 
* Ran doxygen on the code.  This part didn't pass, but I added an issue for it.

**Pull request merged**
